import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const root = new URL('../', import.meta.url)
const packageJson = JSON.parse(await readFile(new URL('package.json', root), 'utf8'))
const html = await readFile(new URL('examples/cdn/index.html', root), 'utf8')
const rootEntry = await readFile(new URL('dist/index.js', root), 'utf8')
const elementEntry = await readFile(new URL('dist/element.js', root), 'utf8')
const defineEntry = await readFile(new URL('dist/element-define.js', root), 'utf8')
const vueEntry = await readFile(new URL('dist/vue.js', root), 'utf8')
const reactEntry = await readFile(new URL('dist/react.js', root), 'utf8')

assert.equal(packageJson.exports['./element/define'].import, './dist/element-define.js')
assert.equal(packageJson.exports['./element/define'].types, './dist/element-define.d.ts')
assert(packageJson.sideEffects.includes('./dist/element-define.js'))
assert.match(defineEntry, /defineAnyoPlayerElement\(\)/)
assert.doesNotMatch(elementEntry, /defineAnyoPlayerElement\(\);/)
assert.doesNotMatch(rootEntry, /from ['"](?:vue|react|react-dom)/)
assert.match(vueEntry, /from ['"]vue['"]/)
assert.match(reactEntry, /from ['"]react['"]/)
assert.match(html, /type="importmap"/)
assert.match(html, /@blcklab\/anyo-player\/element\/define/)
assert(html.includes(`@blcklab/anyo-player@${packageJson.version}`))
assert(html.includes(`@blcklab/anyo@${packageJson.devDependencies['@blcklab/anyo']}`))
assert(html.includes(`@blcklab/sekai64@${packageJson.devDependencies['@blcklab/sekai64']}`))
assert.match(html, /@blcklab\/anyo\/renderer-sekai64/)
assert.match(html, /@blcklab\/anyo\/web-surface/)
assert(html.includes(`@blcklab/anyo@${packageJson.devDependencies['@blcklab/anyo']}/dist/esm/index.js`))
assert(html.includes(`@blcklab/anyo@${packageJson.devDependencies['@blcklab/anyo']}/dist/esm/renderer-sekai64/index.js`))
assert(html.includes(`@blcklab/anyo@${packageJson.devDependencies['@blcklab/anyo']}/dist/esm/web-surface/index.js`))
assert.doesNotMatch(html, /<script[^>]+src=["'][^"']*(?:vue|react)/i)
console.log('Verified CDN import map, side-effect isolation, and no-build custom-element example')
